In [38]:
import pandas as pd
import numpy as np

In [39]:
data = pd.read_csv("insurance.csv")

In [40]:
data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [41]:
data.sex.replace({"male":1,"female":0},inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_20724\3047114968.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.sex.replace({"male":1,"female":0},inplace=True)
C:\Users\hp\AppData\Local\Temp\ipykernel_20724\3047114968.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.sex.replace({"male":1,"female":0},inplace=True)

In [42]:
data

      age  sex     bmi  children smoker     region      charges
0      19    0  27.900         0    yes  southwest  16884.92400
1      18    1  33.770         1     no  southeast   1725.55230
2      28    1  33.000         3     no  southeast   4449.46200
3      33    1  22.705         0     no  northwest  21984.47061
4      32    1  28.880         0     no  northwest   3866.85520
...   ...  ...     ...       ...    ...        ...          ...
1333   50    1  30.970         3     no  northwest  10600.54830
1334   18    0  31.920         0     no  northeast   2205.98080
1335   18    0  36.850         0     no  southeast   1629.83350
1336   21    0  25.800         0     no  southwest   2007.94500
1337   61    0  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [43]:
data.smoker.replace({"yes":1,"no":0},inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_20724\2518070485.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.smoker.replace({"yes":1,"no":0},inplace=True)
C:\Users\hp\AppData\Local\Temp\ipykernel_20724\2518070485.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.smoker.replace({"yes":1,"no":0},inplace=True)

In [48]:
data.region.unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [50]:
region_dumies = pd.get_dummies(data.region).astype(int)

In [54]:
data = pd.concat([data,region_dumies],axis=1)

In [60]:
data.drop(["region"],axis=1,inplace=True)

In [61]:
data

,age,sex,bmi,children,smoker,charges,northeast,northwest,southeast,southwest
0,19,0,27.900,0,1,16884.92400,0,0,0,1
1,18,1,33.770,1,0,1725.55230,0,0,1,0
2,28,1,33.000,3,0,4449.46200,0,0,1,0
3,33,1,22.705,0,0,21984.47061,0,1,0,0
4,32,1,28.880,0,0,3866.85520,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...
1333,50,1,30.970,3,0,10600.54830,0,1,0,0
1334,18,0,31.920,0,0,2205.98080,1,0,0,0
1335,18,0,36.850,0,0,1629.83350,0,0,1,0
1336,21,0,25.800,0,0,2007.94500,0,0,0,1
1337,61,0,29.070,0,1,29141.36030,0,1,0,0

# Multiple Regression

In [66]:
x = data.drop(["charges"],axis=1)
y = data.charges

In [67]:
x

,age,sex,bmi,children,smoker,northeast,northwest,southeast,southwest
0,19,0,27.900,0,1,0,0,0,1
1,18,1,33.770,1,0,0,0,1,0
2,28,1,33.000,3,0,0,0,1,0
3,33,1,22.705,0,0,0,1,0,0
4,32,1,28.880,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...
1333,50,1,30.970,3,0,0,1,0,0
1334,18,0,31.920,0,0,1,0,0,0
1335,18,0,36.850,0,0,0,0,1,0
1336,21,0,25.800,0,0,0,0,0,1
1337,61,0,29.070,0,1,0,1,0,0

In [68]:
y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [69]:
from sklearn.model_selection import train_test_split

In [70]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

In [76]:
x_train.shape

(1070, 9)

In [77]:
x_test.shape

(268, 9)

In [78]:
from sklearn.linear_model import LinearRegression

In [79]:
mlr = LinearRegression()

In [80]:
mlr.fit(x_train,y_train)

LinearRegression()

In [81]:
mlr.coef_

array([ 2.56975706e+02, -1.85916916e+01,  3.37092552e+02,  4.25278784e+02,
        2.36511289e+04,  4.59585244e+02,  8.89079180e+01, -1.98279052e+02,
       -3.50214110e+02])

In [82]:
mlr.intercept_

np.float64(-12390.804294570282)

In [85]:
y_pred_train = mlr.predict(x_train)

In [86]:
y_pred_train

array([ 7094.54007011,  8344.72998713,  9153.77419778, ...,
       11441.08519155, 37314.37460682, 11453.12102783], shape=(1070,))

In [87]:
from sklearn.metrics import r2_score,root_mean_squared_error

In [88]:
root_mean_squared_error(y_train,y_pred_train)

6105.545160099848

In [89]:
r2_score(y_train,y_pred_train)

0.7417255854683333

In [90]:
y_pred_test = mlr.predict(x_test)

In [92]:
root_mean_squared_error(y_test,y_pred_test)

5796.2846592762735

In [93]:
r2_score(y_test,y_pred_test)

0.7835929767120723

In [94]:
def predict_charges(data): 
    return mlr.predict(data)

In [95]:
predict_charges([[25, 1, 26.5, 0, 0, 0, 0, 1, 0]])

C:\Users\hp\Downloads\apps\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([2749.67023389])